@startuml Registration

actor Client as client
participant "API Gateway" as api
participant "Account service" as account_service
database Database as db
database Redis as redis

client -> api : RegData
rnote over client
    e-mail
    sha256(e-mail:pwd)
endrnote
api -> account_service : RegData
account_service -> db : Check e-mail presence
db --> account_service: Abscent
account_service -> account_service : Generate user_id
account_service -> db : Create entry
rnote over account_service
    user_id
    e-mail
    sha256(e-mail:pwd)
endrnote
account_service -> account_service : Generate session token
account_service -> redis : Add record (token, user_id)
account_service -> api : token
api -> client : token

@enduml