prod-build:
	docker build -t registry.gitlab.com/rvr-board/backend/account-service .
	docker push registry.gitlab.com/rvr-board/backend/account-service

dev-build:
	docker build -t board-account-service .